CREATE TABLE ITKSTU.USERLOGIN(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	EMAIL VARCHAR(50),
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	HIGHSCHOOL VARCHAR(50),
	SPORTS VARCHAR(50),
	GPA VARCHAR(4),
	SAT VARCHAR(4),
	UNIVERSITY VARCHAR(50),
	MAJOR VARCHAR(50),
	AWARDS VARCHAR(160),
	CLUBS VARCHAR(160),
	COLOR VARCHAR(10)
);

CREATE TABLE ITKSTU.UNIVERSITIES(
	COLLEGENAME VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	MASCOT VARCHAR(50),
	ADDRESS VARCHAR(50),
	PHONE VARCHAR(10),
	TUITIONNRATE VARCHAR(15),
	ENROLLMENT VARCHAR(15),
	COLOR1 VARCHAR(10),
	COLOR2 VARCHAR(10),
	COLOR3 VARCHAR(10)
);


